DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS movies;
DROP TABLE IF EXISTS actors;

CREATE TABLE actors (
  id SERIAL8 PRIMARY KEY,
  first_name VARCHAR(255),
  last_name VARCHAR(255)
);

CREATE TABLE movies (
  id SERIAL8 PRIMARY KEY,
  title VARCHAR(255),
  genre VARCHAR(255),
  budget INT
);

CREATE TABLE roles (
  id SERIAL8 PRIMARY KEY,
  movie_id INT REFERENCES movies(id) ON DELETE CASCADE,
  actor_id INT REFERENCES actors(id) ON DELETE CASCADE,
  fee INT8
);
